-- Nova Salud - Supabase Database Schema

-- Tabla de productos
CREATE TABLE productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio DECIMAL(10, 2) NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  fecha_vencimiento DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de ventas
CREATE TABLE ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES auth.users(id) NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de detalle_ventas
CREATE TABLE detalle_ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id BIGINT REFERENCES ventas(id) ON DELETE CASCADE NOT NULL,
  producto_id BIGINT REFERENCES productos(id) NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_unitario DECIMAL(10, 2) NOT NULL,
  subtotal DECIMAL(10, 2) NOT NULL
);

-- Habilitar Row Level Security
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_ventas ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para productos
CREATE POLICY "Anyone can read productos" ON productos
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert productos" ON productos
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update productos" ON productos
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete productos" ON productos
  FOR DELETE USING (auth.role() = 'authenticated');

-- Políticas RLS para ventas
CREATE POLICY "Authenticated users can manage ventas" ON ventas
  FOR ALL USING (auth.role() = 'authenticated');

-- Políticas RLS para detalle_ventas
CREATE POLICY "Authenticated users can manage detalle_ventas" ON detalle_ventas
  FOR ALL USING (auth.role() = 'authenticated');

-- Función para actualizar stock automáticamente
CREATE OR REPLACE FUNCTION actualizar_stock()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE productos
    SET stock = stock - NEW.cantidad,
        updated_at = NOW()
    WHERE id = NEW.producto_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para actualizar stock al crear detalle de venta
CREATE TRIGGER trigger_actualizar_stock
AFTER INSERT ON detalle_ventas
FOR EACH ROW
EXECUTE FUNCTION actualizar_stock();