-- Nova Salud - Supabase Database Schema Completo para Botica
-- --------------------------------------------------------

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLAS DE CATÁLOGO / MAESTRAS

-- Tabla de categorías
CREATE TABLE categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  estado BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de proveedores
CREATE TABLE proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social TEXT NOT NULL,
  ruc VARCHAR(11) UNIQUE,
  contacto TEXT,
  telefono VARCHAR(20),
  email TEXT,
  direccion TEXT,
  estado BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de usuarios (Perfiles del sistema / Personal)
CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id UUID REFERENCES auth.users(id), -- Vinculado a Supabase Auth
  nombres TEXT NOT NULL,
  apellidos TEXT NOT NULL,
  rol VARCHAR(50) DEFAULT 'CAJERO', -- ADMIN, CAJERO, FARMACEUTICO
  dni VARCHAR(15) UNIQUE,
  telefono VARCHAR(20),
  email TEXT,
  estado BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. PRODUCTOS E INVENTARIO

-- Tabla de productos (Mejorada)
CREATE TABLE productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_barras VARCHAR(100) UNIQUE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  categoria_id BIGINT REFERENCES categorias(id),
  proveedor_id BIGINT REFERENCES proveedores(id),
  precio DECIMAL(10, 2) NOT NULL,
  precio_compra DECIMAL(10, 2),
  stock INTEGER NOT NULL DEFAULT 0,
  stock_minimo INTEGER DEFAULT 5,
  fecha_vencimiento DATE,
  registro_sanitario VARCHAR(50),
  receta_obligatoria BOOLEAN DEFAULT FALSE,
  laboratorio TEXT,
  estado BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. MOVIMIENTOS Y VENTAS

-- Tabla de ventas (Cabecera)
CREATE TABLE ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES usuarios(id), -- Vendedor / Usuario del sistema
  tipo_comprobante VARCHAR(20) DEFAULT 'TICKET', -- BOLETA, FACTURA, TICKET
  numero_comprobante VARCHAR(50),
  subtotal DECIMAL(10, 2) DEFAULT 0,
  igv DECIMAL(10, 2) DEFAULT 0,
  total DECIMAL(10, 2) NOT NULL,
  metodo_pago VARCHAR(20) DEFAULT 'EFECTIVO', -- EFECTIVO, TARJETA, YAPE, PLIN
  estado VARCHAR(20) DEFAULT 'COMPLETADA', -- COMPLETADA, ANULADA
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de detalle_ventas
CREATE TABLE detalle_ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id BIGINT REFERENCES ventas(id) ON DELETE CASCADE NOT NULL,
  producto_id BIGINT REFERENCES productos(id) NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_unitario DECIMAL(10, 2) NOT NULL,
  subtotal DECIMAL(10, 2) NOT NULL,
  descuento DECIMAL(10, 2) DEFAULT 0
);

-- Tabla de compras (Ingreso de mercadería)
CREATE TABLE compras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_id BIGINT REFERENCES proveedores(id),
  usuario_id BIGINT REFERENCES usuarios(id), -- Usuario que registra la compra
  numero_comprobante VARCHAR(50),
  total DECIMAL(10, 2) NOT NULL,
  estado VARCHAR(20) DEFAULT 'COMPLETADA', -- COMPLETADA, ANULADA
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de detalle_compras
CREATE TABLE detalle_compras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id BIGINT REFERENCES compras(id) ON DELETE CASCADE NOT NULL,
  producto_id BIGINT REFERENCES productos(id) NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_compra DECIMAL(10, 2) NOT NULL,
  lote VARCHAR(50),
  fecha_vencimiento DATE,
  subtotal DECIMAL(10, 2) NOT NULL
);

-- 5. CAJA
CREATE TABLE caja_movimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES usuarios(id), -- Usuario de caja
  tipo_movimiento VARCHAR(20) NOT NULL, -- APERTURA, CIERRE, INGRESO, EGRESO
  monto DECIMAL(10, 2) NOT NULL,
  concepto TEXT,
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------------------
-- CONFIGURACIÓN DE SEGURIDAD Y TRIGGERS
-- --------------------------------------------------------

-- Habilitar Row Level Security
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE caja_movimientos ENABLE ROW LEVEL SECURITY;

-- Políticas Base (Autenticados pueden realizar operaciones completas)
CREATE POLICY "Auth access categorias" ON categorias FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth access proveedores" ON proveedores FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth access usuarios" ON usuarios FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Anyone can read productos" ON productos FOR SELECT USING (true);
CREATE POLICY "Auth access productos" ON productos FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth access ventas" ON ventas FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth access detalle_ventas" ON detalle_ventas FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth access compras" ON compras FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth access detalle_compras" ON detalle_compras FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth access caja" ON caja_movimientos FOR ALL USING (auth.role() = 'authenticated');

-- --------------------------------------------------------
-- FUNCIONES Y TRIGGERS (INVENTARIO AUTOMÁTICO)
-- --------------------------------------------------------

-- Función para actualizar stock por VENTAS (Resta)
CREATE OR REPLACE FUNCTION actualizar_stock_venta()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE productos
    SET stock = stock - NEW.cantidad,
        updated_at = NOW()
    WHERE id = NEW.producto_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_restar_stock
AFTER INSERT ON detalle_ventas
FOR EACH ROW
EXECUTE FUNCTION actualizar_stock_venta();

-- Función para actualizar stock por COMPRAS (Suma)
CREATE OR REPLACE FUNCTION actualizar_stock_compra()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE productos
    SET stock = stock + NEW.cantidad,
        precio_compra = NEW.precio_compra,
        updated_at = NOW()
    WHERE id = NEW.producto_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_sumar_stock
AFTER INSERT ON detalle_compras
FOR EACH ROW
EXECUTE FUNCTION actualizar_stock_compra();